api:
  dashboard: false
ping: {}

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  kubernetesIngress:
    ingressClass: external-traefik-azure
  kubernetesCRD:
    ingressClass: external-traefik-azure
  file:
    filename: /etc/traefik/routes.yml
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: admin@ringen.cloud
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

log:
  level: DEBUG

accessLog: {}
